### ISSUE TITLE
What is the added value for VaultTemplate when using Key/Value ?

### ISSUE THREAD

**Issue by zak905** [spring-projects/spring-vault#380] opened 2019-02-25 10:26 UTC
Hello, 

After struggling with paths, I could submit my keys/value secret using the vault template in this way: 

```
template.opsForKeyValue("secret/data/myapp", VaultKeyValueOperationsSupport.KeyValueBackend.KV_1).put("secret1", "{\"data\":{\"test\":\"test\"},\"options\":{}}'");
```

The `test=test` is submited at `secret/myapp/secret1`. I was just wondering about the real value here for using VaultTemplate, since the same thing can be done with a `RestTemplate`, and with the same effort. One would expect the VaultTemplate to make things a little bit easier, than using any http client (e.g, wrapping the key/values internally into this payload `"{\"data\":{\"test\":\"test\"},\"options\":{}}'"` and also adding automatically `/data` since this is not part of the real path, but only using by vault when adding the data).

**Comment by mp911de** [comment] 2019-02-25 10:49
Thanks for your question.

A bit of history and how things have developed plays into that. Until Vault 0.10.0, we had only a single generic secret Key-Value (leaving the other backends like database out of scope for brevity). If you wanted to interact with any type of Vault API, `VaultTemplate` is the way to go. It encapsulates session-affinity, handles HTTP status-based responses, and provides routing to multiple Vault servers.

With Vault 0.10.0, the versioned Key-Value template was introduced and this broke basically all client implementations that were used to the simple path and unwrapped data scheme.
As you have noticed, the versioned key-value API requires an additional path segment and wrapping/unwrapping of the `date` in yet another `data` object.

Therefore, we had to introduce another abstraction to interact specifically with Key-Value backends and this adds another layer of complexity.

`VaultTemplate` is the basic API on which all other Spring Vault functionality is built on. It's the foundation of all API access and it corresponds with what you get with `vault write {path}` and `vault read {path}`. The same thing can be done with `curl -H"X-Vault-Token: " …`. Trying to use the Key-Value Backend v2 with `vault write …` fails and so one must use `vault kv get …`.

Why stick people with the Vault CLI? Because it makes things easier. Why would one use `VaultTemplate`? Because it makes as well things easier.

FTR: We are not happy how the versioned Key-Value backend was introduced nor how compatibility is emulated. HashiCorp folks have decided to walk their route and everyone else has either to follow, to build ugly hacks or to not support Key-Value v2.

**Comment by mp911de** [comment] 2019-02-26 07:51
Closing as the issue is answered and there were no follow-up items to clarify.

**Comment by zak905** [comment] 2019-02-26 09:02
Thanks for the clarifying. Before closing the issue :), I wanted to add that Vault may make things easier if one is using advanced features, it just was not easy for me to find out how to submit a key-value, as there is no example. I had to put break points to understand. I understand that it is not easy to follow up with breaking API changes. To put the problem simply: 

- when doing something like:  ` template.opsForKeyValue("secret/data/myapp", VaultKeyValueOperationsSupport.KeyValueBackend.KV_1).put("mykey", "myvalue");`

I would expect that `vault kv get secret/myapp` returns `mykey=value`, which would in somehow mimic the behavior of java `Map` put method. 

But in this case, the value is put in `secret/myapp/mykey` and additionally the value/key value has to be wrapped into POJO.  which seems to be kind of broken, no ? 

If this makes, I can contribute with a PR, my knowledge of vault is  limited though.

**Comment by mp911de** [comment] 2019-02-26 09:39
[Here's an example for Key-Value API usage](https://github.com/mp911de/spring-cloud-vault-config-samples/blob/master/spring-vault/hello-world/src/test/java/example/helloworld/KeyValueTests.java). We have a dedicated [repo](https://github.com/mp911de/spring-cloud-vault-config-samples/) that contains some samples.

The entire Template API works entity/object-oriented in the sense that the value is represented as JSON stored under a key. So from the example above, `put("mykey", "myvalue");` the value `myvalue` is converted to JSON.

Feel free to submit a pull request that explains Key-Value usage within the reference documentation as this is a useful information.

**Comment by mp911de** [comment] 2019-03-11 07:54
Closing this one as there isn't anything left to do.

**Closed by mp911de** 2019-03-11 07:54 UTC
Labels: for: stackoverflow
