### ISSUE TITLE
Unidentifiable RoleId and SecretId objects in the AppRole example

### ISSUE THREAD

**Issue by SladeRun14** [spring-projects/spring-vault#183] opened 2017-12-11 13:06 UTC
In 
`AppRoleAuthenticationOptions options = 
        AppRoleAuthenticationOptions.builder()
                .roleId(RoleId.provided("…"))
                .secretId(SecretId.wrapped(VaultToken.of("…")))
                .build();`

The `RoleId` and `SecretId` classes don't seem to exist anywhere.  If this is true, shouldn't the example code be updated? Or if they do exist, a reference to the import would be helpful.

**Comment by mp911de** [comment] 2017-12-12 14:21
Duplicate of #179. `RoleId` and `SecretId` are inner types of `AppRoleAuthenticationOptions`. They should be public which is fixed with #179 but not yet released. Care to give the current snapshot a try (`2.0.0.BUILD-SNAPSHOT`).

**Comment by mp911de** [comment] 2018-01-16 13:40
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by mp911de** 2018-01-16 13:40 UTC
Labels: feedback requested
