### ISSUE TITLE
Rotate non-renewable secrets

### ISSUE THREAD

**Issue by chickenbane** [spring-projects/spring-vault#215] opened 2018-03-10 17:10 UTC
I have Vault credentials that are rotating every hour. I was not able to use the handy `@VaultPropertySource` annotation but was able to replicate its functionality with two beans:

```java
@Bean
public LeaseAwareVaultPropertySource leaseAwareVaultPropertySource(
@Value("${stspath}") String stsPath,
SecretLeaseContainer secretLeaseContainer) {
  RequestedSecret secret = RequestedSecret.rotating(stsPath);
  PropertyTransformer propertyTransformer = PropertyTransformers.propertyNamePrefix("sts.");
  return new LeaseAwareVaultPropertySource(stsPath, secretLeaseContainer, secret, propertyTransformer);
}

@Bean
public static PropertySourcesPlaceholderConfigurer pspc() {
  return new PropertySourcesPlaceholderConfigurer() {
    @Override
    public void postProcessBeanFactory(ConfigurableListableBeanFactory beanFactory) throws BeansException {
      super.postProcessBeanFactory(beanFactory);

      ConfigurableEnvironment env = beanFactory.getBean(ConfigurableEnvironment.class);
      MutablePropertySources mutablePropertySources = env.getPropertySources();

      Collection<? extends PropertySource<?>> propertySources = beanFactory
        .getBeansOfType(org.springframework.vault.core.env.LeaseAwareVaultPropertySource.class)
        .values();

      for (PropertySource<?> vaultPropertySource : propertySources) {
        if (propertySources.contains(vaultPropertySource.getName())) {
          continue;
        }
        mutablePropertySources.addLast(vaultPropertySource);
      }
    }
  };
}
```

This is able to get the initial properties in the `Environment`, but when the tokens expire they are not renewed. Do I need to do more to renew the credentials with Vault and publish them to the Spring `Environment`?

**Comment by chickenbane** [comment] 2018-03-10 17:36
I think the issue is due to LeaseRenewalScheduler.isLeaseRenewable() in SecretLeaseContainer.  Inspecting my lease I see I have a non-null leaseId with renewable=false, but for rotating credentials the code requires leaseId == null:

```
			if (!lease.hasLeaseId() && requestedSecret.getMode() == Mode.ROTATE) {

```

**Comment by mp911de** [comment] 2018-03-13 11:20
Let's go back for a moment to understand what's happening here. Do you want to rotate a secret that does not have a lease id associated?

**Comment by chickenbane** [comment] 2018-03-13 15:56
Sure. To take a step back I would like rotating secrets when I specify
RequestedSecret.ROTATE.

I would like to understand the logic in the code around checking for the
existence of a lease id. According to:

https://www.vaultproject.io/docs/concepts/lease.html

A dynamic secret will always have a lease id, which matches my experience.
Is there another mechanism for obtaining and renewing a rotating secret in
spring vault?

**Comment by mp911de** [comment] 2018-03-13 19:19
Spring Vault currently rotates only secrets that:

1. Have a lease associated and are renewable (e.g. database backend)
2. Have no lease associated (e.g. key/value generic backend)

Secrets without a renewable lease are not rotated. We should consider rotating secrets that are non-renewable since renewal is only an intermediate step to keep the lease alive.

**Comment by joeyslalom** [comment] 2018-03-13 21:44
My use case is the AWS STS Assume Role: https://www.vaultproject.io/docs/secrets/aws/index.html#sts-assumerole

This delivers secrets that are not renewable but have a lease associated with them.  The good news is my PR #220 works with these credentials and rotates them as configured by this issue.  If there is an alternative implementation that you'd prefer I can assist, though I thought the changes were pretty minor and still pass all your tests.

**Comment by mp911de** [comment] 2018-03-14 07:34
Thanks a lot for clarification. From that perspective, this issue is a rather a bug that we need to fix. I updated the ticket accordingly. Will take a look at your pull request.

**Comment by joeyslalom** [comment] 2018-03-16 17:21
Thanks!  Just migrated from another solution to Spring Vault and love the library.  Let me know if you need assistance with the fix; for example in start(RequestedSecret, LeaseRenewalScheduler) my leaseId looks like:

aws/sts/{my sts role}/756170a9-243f-0418-fe62-df6e70652628

so without moving the if (isRotatingGenericSecret()) before the StringUtils.hasText(secrets.getLeaseId()) check the code would try to renew on the leaseId rather than rotating the secret.

**Comment by mp911de** [comment] 2018-03-20 11:42
I'd apply a slightly different approach than proposed in #220. As we already know that the lease isn't suitable for renewal, we can directly emit an expired event and rotation will happen directly.

**Comment by mp911de** [comment] 2018-03-20 11:53
I pushed a fix, snapshot builds are available from repo.spring.io. Care to give the snapshot builds a spin?

**Comment by joeyslalom** [comment] 2018-03-21 17:14
Hello, I tested the release today, 1.1.2.BUILD-SNAPSHOT.  It did not renew my tokens. :(

**Comment by mp911de** [comment] 2018-03-22 08:29
I'll take another look. In that context: What should happen if rotation fails (connection timeout, connection refused, HTTP 503 response)? Right now, renewal/rotation stops and one can subscribe to events to hook into recovery.

**Comment by mp911de** [comment] 2018-03-22 08:59
Care to provide a reproducer? Running the code from above against `spring-vault-core-1.1.2.BUILD-20180320.150107-8` or newer works for me and I'm not able to reproduce the issue. Thanks!

**Comment by joeyslalom** [comment] 2018-03-22 15:46
Nothing seems to happen - I used addLeaseListener() and addErrorListener() but neither callback occurs.  With my PR I would get regular SecretLeaseCreatedEvents.

I will try to look into it more this weekend, from a fast glance through the changes I'd guess my Lease is being created here:

https://github.com/spring-projects/spring-vault/blob/28932b75592f6166855be3157a13f17077a88c7a/spring-vault-core/src/main/java/org/springframework/vault/core/lease/SecretLeaseContainer.java#L308

But this sets leaseId to null, which causes the new isLeaseRotateOnly() to return false

**Comment by joeyslalom** [comment] 2018-03-22 15:50
Re: rotation fails, it would be helpful if there was an easy way to configure retry with backoff.  Doesn't need to be the default, but it is such a common use-case so something out of the box would be awesome.

**Comment by mp911de** [comment] 2018-03-23 07:56
Please provide a reproducer (either steps to reproduce or code). Without being able to reproduce I'd consider the issue resolved.

**Comment by joeyslalom** [comment] 2018-03-27 15:54
I consider resolved! I tried to create a repro with 2.1.0.BUILD-20180321.143110-13 but it rotated my secret.  I think in my comment about 1.1.2.BUILD-SNAPSHOT my project was misconfigured to take your latest BUILD-SNAPSHOT.  But with a logging lease listener I see the SecretLeaseExpiredEvent followed by the SecretLeaseCreatedEvent.  Thanks for your help!

**Comment by mp911de** [comment] 2018-03-28 14:24
Thanks a lot for re-checking the issue. Closing this one as solved.

**Closed by mp911de** 2018-03-28 14:24 UTC
Labels: bug

**Comment by kalpit012** [comment] 2019-09-01 20:02
Spring Vault currently rotates only secrets that:
 1. Have a lease associated and are renewable (e.g. database backend)
 2. Have no lease associated (e.g. key/value generic backend)

Here what do you mean by secrets ? Is it token .
What will happen for vault consul configuration? Say I have spring cloud vault consul and have bootstrap.yaml with Backend for database and consul.
Would spring vault on rotate lease update the token of consul stored within Vault and notify the consul. 
If not then do we have to use addLeaselistener to read the event and on rotate event update the token of consul (consul/creds/app) that's within the sessionManager. At present consul/creds/appname is readonly and it's token cannot be updated ? 

After an hour the application gets 403 error code when there is a event to Rotate lease and consul is not able to connect to app/appname KV store. 

It looks like connection issues between vault and consul based on token.
