### ISSUE TITLE
Introduce LifecycleAwareSessionManager token renew strategies

### ISSUE THREAD

**Issue by vrudikov** [spring-projects/spring-vault#181] opened 2017-12-04 09:55 UTC
Hi!
So my story: we have Cassandra as Backend storage and sometimes it doesn't response fast because of load(or background tasks on Cassandra server virtual). LifecycleAwareSessionManager.renewToken throws an exception at line 182:
```
throw new VaultException(VaultResponses.getError(e.getResponseBodyAsString()));
```
In 10-20 seconds Cassandra becomes available, but it's too late - token was not re-newed, lease dies and Vault deletes a Cassandra user.

![pasted image at 2017_11_30 04_31 pm](https://user-images.githubusercontent.com/493714/33543377-dce211ee-d8e7-11e7-9205-38f50bc42465.png)

So my proposal is to have token renew strategies:
1) So first of all this constant - "5 seconds before token expiration" should go to strategy. Because we should be flexible
2) I think we should have retry setup in strategy

Example of strategy. Strategy policy(rules):
- Token re-new starts before 60 seconds of it's expiration(REFRESH_PERIOD_BEFORE_EXPIRY is configurable)
- we have 5 tries to renew(configurable)

Logic flow: check re-try count try to re-new - if failed schedule a re-new in 10 seconds
if after 5 tries token is not re-newed or token reached his expiration time.... DIE! :)

Thoughts?

**Comment by mp911de** [comment] 2017-12-06 05:42
Hey Valentin, thanks a lot for raising the issue. Refresh period before expiry isn't a constant, it's a default value passed into `FixedTimeoutRefreshTrigger`. You can adjust that value by passing a `FixedTimeoutRefreshTrigger` instance configured to your needs while creating `LifecycleAwareSessionManager`.

Please upgrade to a more recent version as 1.1.x addresses some renewal concerns. Retries won't help here:

* If your backend is slow, it's unusable for generating tokens and reading/writing data. You maybe get a token but you can't use it. We drop the token if we can't refresh it. 
* Subsequent requests will attempt re-login and once your backend is up again, you can obtain a token again and Vault is usable.

Adding retries only increases complexity. Checkout the latest version and give it a spin with a customized timeout. Happy to receive feedback on how it worked out for you.

**Comment by mp911de** [comment] 2018-01-24 07:39
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by mp911de** 2018-01-24 07:39 UTC

**Comment by radarsh** [comment] 2019-04-08 15:54
> If your backend is slow, it's unusable for generating tokens and reading/writing data. You maybe get a token but you can't use it. We drop the token if we can't refresh it.

I understand your point but sometimes we are left with no choice but to build some resiliency around a troublesome connectivity to Vault. In our case, we are considering extending / re-implementing `LifecycleAwareSessionManager` because we want to slap a bit of Spring Retry around the renewal logic and also attempt to renew well in advance, instead of learning 5 seconds before the token expires that there is a problem and we cannot renew at all. However, this is leading to a lot of copied Spring Vault code in our codebase as some of the methods seem to have not been designed with extensibility in mind.

Also, `LifecycleAwareSessionManager` [claims that if there is an error during renewal, it resets the token and performs a re-login](https://github.com/spring-projects/spring-vault/blob/master/spring-vault-core/src/main/java/org/springframework/vault/authentication/LifecycleAwareSessionManager.java#L202). But where is the re-login happening? I believe one has to invoke `getSessionToken` again in order to force that.

**Comment by mp911de** [comment] 2019-04-08 20:01
>  But where is the re-login happening? I believe one has to invoke getSessionToken again in order to force that.

Exactly. 

Let me know if there are functionality that you would like to re-use. Happy to discuss various approaches in a new ticket.

**Comment by radarsh** [comment] 2019-04-09 14:13
Done. Created #415

**Comment by mechero** [comment] 2019-05-24 13:05
Hi, 

I know this issue is closed but just to be sure, what is the suggested approach when the Vault server goes down for a while and the application can't renew the token? 

What happens now is that the exception is thrown and, even though `LifecycleAwareSessionManager` claims to handle that by itself (as stated above), this is not happening. Since `token` is an empty `Optional`, it won't reschedule a new `renewToken()` call. Therefore, this block is never reached again:

```
		Optional<TokenWrapper> token = this.token;
		if (!token.isPresent()) {
			getSessionToken();
			return false;
		}
```

So it's actually not doing a re-login by itself. Is this the expected behavior? If it is, please let me know what you suggest to do in that situation to detect that issue and programmatically call `getSessionToken()` again. 

Thanks!

**Comment by mp911de** [comment] 2019-05-24 14:09
Renewal is stopped upon exception. 

> So it's actually not doing a re-login by itself. 

Re-login happens on the next call to `getSessionToken()`. If this does not work, please file a new ticket.

**Comment by mechero** [comment] 2019-05-27 09:39
Created https://github.com/spring-projects/spring-vault/issues/426
Thanks!
