### ISSUE TITLE
Add ca_chain property to Certificate

### ISSUE THREAD

**Issue by bshelton** [spring-projects/spring-vault#746] opened 2023-01-12 18:17 UTC
As of Vault 1.11, the generate cert and key pki endpoint now returns the ca_chain. Is this something that we can add? If so, I will submit a PR for this. 

Reference: https://developer.hashicorp.com/vault/api-docs/secret/pki#generate-certificate-and-key

Solution: 
Update spring-vault/blob/main/spring-vault-core/src/main/java/org/springframework/vault/support/Certificate.java CertificateBundle.java

**Comment by mp911de** [comment] 2023-03-17 09:31
This looks like a duplicate of #648. Can you confirm whether this works for you?

**Closed by mp911de** 2023-03-17 09:31 UTC
