### ISSUE TITLE
Add support for /pki/sign/:name

### ISSUE THREAD

**Issue by cbchhaya** [spring-projects/spring-vault#168] opened 2017-11-01 07:41 UTC
For a configured PKI backend, add ability to obtain a signed certificate in response to a CSR. Most of the properties and validation are already present in `VaultCertificateRequest` type, so can either extend it or add a new type `VaultCertificateSigningRequest`. Happy to submit patch with functionality.

**Comment by mp911de** [comment] 2017-11-01 09:36
That's [already in place](https://github.com/spring-projects/spring-vault/blob/master/spring-vault-core/src/main/java/org/springframework/vault/core/VaultPkiOperations.java#L75-L76) for 2.0. Duplicate of #125.

**Closed by mp911de** 2017-11-01 09:36 UTC
