### ISSUE TITLE
ThreadPoolTaskScheduler needs to call initialize() in AbstractVaultConfiguration

### ISSUE THREAD

**Issue by RaimondKempees** [spring-projects/spring-vault#552] opened 2020-04-28 15:50 UTC
When using Spring Vault in Spring Cloud Config and health checks are enabled, the initial check fails with: "ThreadPoolTaskScheduler not initialized" in ScheduledExecutorService getScheduledExecutor().

This is because in AbstractVaultConfiguration it's instantiated like this:

`	
	@Bean("vaultThreadPoolTaskScheduler")
	public ThreadPoolTaskScheduler threadPoolTaskScheduler() {

		ThreadPoolTaskScheduler threadPoolTaskScheduler = new ThreadPoolTaskScheduler();

		threadPoolTaskScheduler
				.setThreadNamePrefix("spring-vault-ThreadPoolTaskScheduler-");
		threadPoolTaskScheduler.setDaemon(true);

		return threadPoolTaskScheduler;
	}`

When I add:

`threadPoolTaskScheduler.initialize()` in an overridden bean method, the initial health check works fine.

Version affected is **spring-vault-core-2.2.2.RELEASE**.

**Comment by mp911de** [comment] 2020-04-28 15:57
Can you provide a reproducer?

**Comment by RaimondKempees** [comment] 2020-04-28 17:22
I think it's reproducible by the following steps:

1. Add the Spring Cloud Config and Vault  dependencies, so both Git and Vault can be used

`        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-config-server</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-vault-config</artifactId>
        </dependency>`

2. Add the vault config and spring profiles to **bootstrap.properties**:

`#Needed for both git and vault
spring.profiles.active=git, vault

spring.cloud.config.server.vault.backend=*****
spring.cloud.config.server.vault.kv-version=2

spring.cloud.config.server.vault.default-key=*****

spring.cloud.config.server.vault.ssl.trust-store-password=*****
spring.cloud.config.server.vault.ssl.trust-store=classpath:*****.jks

#switching this over to Cloud Config.
spring.cloud.vault.enabled=false`

Note that I've disabled the Spring Cloud Vault core as else you get both Cloud Config and Cloud Vault initializing things.

Then, in application.properties you put the git repo you also want to access. 

That's pretty much it. Note that even in this setup AbstractVaultConfiguration is used by Spring Cloud config (through SpringVaultClientConfiguration) and the ThreadPoolTaskScheduler is created as it should - it's just that the scheduledExecutor is initialized yet, because I *think* that afterPropertiesSet() isn't called yet in the ThreadPoolTaskScheduler.

**Comment by mp911de** [comment] 2020-04-28 17:42
Thanks. That looks like a duplicate of https://github.com/spring-cloud/spring-cloud-config/issues/1556

**Comment by RaimondKempees** [comment] 2020-04-28 17:46
Looks like it. However, if multiple profiles and repos should be supported by Spring Cloud Config, then I do not think it's a config error as stated in the other issue, but a bug. 

In any case - I'll let you guys decide. :) Thanks for looking into it!

**Closed** 2020-04-28 17:49 UTC
Labels: status: duplicate
