### ISSUE TITLE
Change in Vault API version

### ISSUE THREAD

**Issue by anarwal27** [spring-projects/spring-vault#283] opened 2018-08-17 12:41 UTC
New vault installation by default use version 2 of hashicorp APIs for KV type secret engine and the path used by version 2 APIs is 'secret/data/foo' instead of 'secret/foo'. Also the way data being read by new version expects data to be sent in data block for POST/PUT calls. Example:
Spring suggests to use 
{
'val1': 'val2'
}
whereas version 2 APIs expect
{
"data": {
        'foo': 'bar'
  },
}
Probably an update needs to be made to API calls according to new version.

**Comment by mp911de** [comment] 2018-08-17 15:59
Duplicate of #239.

**Closed by mp911de** 2018-08-17 15:59 UTC
