### ISSUE TITLE
Leases no longer revoked after stopping SecretLeaseContainer #855

### ISSUE THREAD

**Issue by NoureddineDahmen** [spring-projects/spring-vault#862] opened 2024-04-05 12:31 UTC
Hello @mp911de  i just create the issue from another  Leases no longer revoked after stopping SecretLeaseContainer #855

Hello @mp911de , I'm sorry for the delay to give feedback .
In Debug , the method SecretLeaseContainer.destroy() is not called when we use ConfigData and it well called when we use Boostrap Config.

Best Regards,

**Comment by mp911de** [comment] 2024-04-05 15:00
Thanks a lot for the detail. That helps to isolate the problem.

**Comment by mp911de** [comment] 2024-04-08 07:41
Duplicate of #855

**Closed by mp911de** 2024-04-08 07:41 UTC
