### ISSUE TITLE
Vault 0.10+ key value store v2 support

### ISSUE THREAD

**Issue by nikoncode** [spring-projects/spring-vault#242] opened 2018-04-12 10:50 UTC
Hi guys.

Vault v 0.10 provides new version of key/value storage by default. Of course using new version of vault you still can configure kv store v1 and it works perfectly with spring-vault library, also I think application code can be adjusted, but I found following differences. And finally, v2 supports versioning and configuration endpoints.

Do you have a plan to upgrade library to provide transparent ability to use v1 and v2 without any changes in code?

|Operation|Difference|
|---|---|
|Read|There is only difference in path.|
|List|There is only difference in path.|
|Create/Update|Difference in path and new version uses POST for both update and create operations. + for v2 payload should be wrapped into "data" object.|
|Remove|Difference in path.|

Docs:
https://www.vaultproject.io/api/secret/kv/kv-v1.html
https://www.vaultproject.io/api/secret/kv/kv-v2.html

**Comment by mp911de** [comment] 2018-04-12 11:46
Duplicate of #239

**Comment by mp911de** [comment] 2018-04-12 11:46
We can't really provide a transparent interface as all operations need to stay aware they are using a versioned backend.

**Closed by mp911de** 2018-04-12 11:46 UTC

**Comment by mp911de** [comment] 2018-04-20 16:13
We added a dedicated Key-Value API with #246 to provide at least read/list/delete methods in a consistent form for versioned and non-versioned backends. Updates require specific inputs  (e.g. version number for CAS) and reading through the new API is limited as it strips off all versioning details.
