### ISSUE TITLE
Expired leases do are not rotated on secret renewal

### ISSUE THREAD

**Issue by dmitrius** [spring-projects/spring-vault#319] opened 2018-10-05 12:10 UTC
Hello,

I am facing an issue with Vault leases that have to be rotated. 
The observed behavior was that a `VaultException` was thrown that was printed in the log saying that 

```
2018-10-04 10:28:20.974  WARN 16528 --- [g-Cloud-Vault-1] LeaseEventPublisher$LoggingErrorListener : [RequestedSecret [path='rabbitmq/creds/rabbitmq-role', mode=ROTATE]] Lease [leaseId='rabbitmq/creds/rabbitmq-role/Ec0v62njpldzcrVdVAjLncwM', leaseDuration=PT10S, renewable=true] Status 400: lease expired

org.springframework.vault.VaultException: Status 400: lease expired
        at org.springframework.vault.client.VaultResponses.buildException(VaultResponses.java:63) ~[spring-vault-core-2.0.1.RELEASE.jar!/:2.0.1.RELEASE]
        at org.springframework.vault.core.VaultTemplate.doWithSession(VaultTemplate.java:310) ~[spring-vault-core-2.0.1.RELEASE.jar!/:2.0.1.RELEASE]
        at org.springframework.vault.core.lease.SecretLeaseContainer.renew(SecretLeaseContainer.java:597) [spring-vault-core-2.0.1.RELEASE.jar!/:2.0.1.RELEASE]
        at org.springframework.vault.core.lease.SecretLeaseContainer.doRenewLease(SecretLeaseContainer.java:564) [spring-vault-core-2.0.1.RELEASE.jar!/:2.0.1.RELEASE]
        at org.springframework.vault.core.lease.SecretLeaseContainer.lambda$scheduleLeaseRenewal$0(SecretLeaseContainer.java:486) 
```

and the expired lease was not requested again. 

So my take is that the piece of code has an issue in the try-catch block of SecretLeaseContainer.doRenewLease(). 
An exception of `HttpStatusCodeException` is expected but the `VaultException` is actually thrown.
And the `VaultException` is not inherited from the `HttpStatusCodeException`.
So that the handler code is missed and another handler for `RuntimeException` is invoked instead.

A quick fix is to add an exception handler for the `VaultException` that will ressemble the logic of HttpStatusCodeException handler:

SecretLeaseContainer
```
	protected Lease doRenewLease(RequestedSecret requestedSecret, Lease lease) {

		try {
			Lease renewed = lease.hasLeaseId() ? renew(lease) : lease;

			if (!renewed.hasLeaseId() || renewed.getLeaseDuration().isZero()
					|| renewed.getLeaseDuration().getSeconds() < minRenewal.getSeconds()) {

				onLeaseExpired(requestedSecret, lease);
				return Lease.none();
			}

			return renewed;
		}
// Quick fix - add a handler for a VaultException
		catch (VaultException e) {

			if (e.getMessage().contains("Status 400")) {
				onLeaseExpired(requestedSecret, lease);
			}

			onError(requestedSecret,
					lease,
					new VaultException(String.format("Cannot renew lease: %s",
							VaultResponses.getError(e.getMessage()))));
		}
		catch (HttpStatusCodeException e) {

			if (e.getStatusCode() == HttpStatus.BAD_REQUEST) {
				onLeaseExpired(requestedSecret, lease);
			}

			onError(requestedSecret,
					lease,
					new VaultException(String.format("Cannot renew lease: %s",
							VaultResponses.getError(e.getResponseBodyAsString()))));
		}
		catch (RuntimeException e) {
			onError(requestedSecret, lease, e);
		}

		return Lease.none();
	}

	private Lease renew(Lease lease) {

		return operations.doWithSession(restOperations -> leaseEndpoints.renew(lease,
				restOperations));
	}

VaultOperations
	<T> T doWithSession(RestOperationsCallback<T> sessionCallback) throws VaultException,
			RestClientException;

VaultTemplate
	public <T> T doWithSession(RestOperationsCallback<T> sessionCallback) {

		Assert.notNull(sessionCallback, "Session callback must not be null");

		try {
			return sessionCallback.doWithRestOperations(sessionTemplate);
		}
		catch (HttpStatusCodeException e) {
			throw VaultResponses.buildException(e);
		}
	}

public abstract class HttpStatusCodeException extends RestClientResponseException {..}
public class RestClientResponseException extends RestClientException {..}
public class RestClientException extends NestedRuntimeException {..}

public class VaultException extends NestedRuntimeException {..}

public abstract class NestedRuntimeException extends RuntimeException {..}
```

Regards,
Dmitri

**Comment by mp911de** [comment] 2018-10-05 13:16
Good catch and thanks for looking into the issue. The bug is, as described, that we catch `HttpStatusCodeException` whereas we should expect `VaultException` and check there for a causing `HttpStatusCodeException`. Changing `SecretLeaseContainer.doRenew(…)` to catch/inspect the exception and changing `VaultResponses` to attach the cause exception to `VaultException` should fix the issue.

**Comment by mp911de** [comment] 2018-10-10 07:15
That's fixed now.

**Closed** 2018-10-10 07:15 UTC
Labels: type: bug
