### ISSUE TITLE
Actuator Refresh does not put back secrets onto the propertysource

### ISSUE THREAD

**Issue by krisiye** [spring-projects/spring-vault#633] opened 2021-02-26 01:08 UTC
Noticed that upon performing an `/actuator/refresh` we lose the environment variables under the property sources. Upon further debugging, it appears to be an out-of-order problem, where a refresh does request any new creds from the respective backends such as consul-kv, aws etc where old secrets are removed and new secrets are replaced onto the property source. However, this is also followed upon by a revoke, which removes the newly placed secrets from the property sources.

The root cause appears to be upon refresh the lease container, seems to be calling start() followed by destroy(). Sample debug logs showing the order of events upon a refresh which should ideally be reversed (revoke existing lease first and properties, and then fetch new secrets and inject into propertysource):

```

2021-02-26 00:43:29.401 DEBUG 1 --- [nio-8081-exec-3] o.s.v.c.e.LeaseAwareVaultPropertySource  : Requesting secrets from Vault at consul-kv/creds/spring-boot-example using ROTATE

SecretLeaseCreatedEvent >>>

2021-02-26 00:43:29.487  INFO 1 --- [nio-8081-exec-3] o.s.v.c.e.LeaseAwareVaultPropertySource  : lease event clearing properties: {}
2021-02-26 00:43:29.487  INFO 1 --- [nio-8081-exec-3] o.s.v.c.e.LeaseAwareVaultPropertySource  : lease event putAll: {spring.cloud.consul.config.acl-token=xxx, spring.cloud.consul.discovery.acl-token=xxx}

BeforeSecretLeaseRevocationEvent >>>

2021-02-26 00:43:29.922  INFO 1 --- [nio-8081-exec-3] o.s.v.c.e.LeaseAwareVaultPropertySource  : leaseEvent: org.springframework.vault.core.lease.event.BeforeSecretLeaseRevocationEvent[source=RequestedSecret [path='consul-kv/creds/spring-boot-example', mode=ROTATE]]
2021-02-26 00:43:29.922  INFO 1 --- [nio-8081-exec-3] o.s.v.c.e.LeaseAwareVaultPropertySource  : lease event clearing properties: {spring.cloud.consul.config.acl-token=xxx, spring.cloud.consul.discovery.acl-token=xxx}

```

Confirmed this behavior with consul and aws backends.

Spring Boot: `2.4.2`
spring cloud version: `2020.0.1`
spring-cloud-vault-config-consul: `3.0.1`
spring-cloud-vault-config-aws: `3.0.1`
spring-vault-core: `2.3.0`, `2.4.0-SNAPSHOT`

**Comment by mp911de** [comment] 2021-03-09 13:40
Paging @spencergibb. Refreshscope originates from Spring Cloud so this is at least a ticket to be continued in Spring Cloud Vault. I'm not sure there's something we can really do here.

**Comment by mp911de** [comment] 2021-03-09 15:05
No, there's no use of `RefreshScope` in Spring Cloud Vault.

**Comment by krisiye** [comment] 2021-03-09 15:42
@spencergibb  @mp911de  - If it helps it's the same kind of behavior documented here - https://gitmemory.com/issue/spring-cloud/spring-cloud-commons/833/780892068 I can confirm that it does not happen when using config data API. Only happens with legacy bootstrap processing.

**Comment by spencergibb** [comment] 2021-03-09 16:56
Then this is a duplicate of https://github.com/spring-cloud/spring-cloud-commons/issues/833

**Closed by spencergibb** 2021-03-09 16:56 UTC
