### ISSUE TITLE
Add authentication path customization in EnvironmentVaultConfiguration

### ISSUE THREAD

**Issue by hitenny** [spring-projects/spring-vault#462] opened 2019-08-22 18:25 UTC
I am using spring vault to access Vault from Spring boot app running in Kubernetes. 

**Version**

    <dependency>  
           <groupId>org.springframework.vault</groupId>  
           <artifactId>spring-vault-core</artifactId>  
           <version>2.1.3.RELEASE</version>  
    </dependency>
  

**Config**  

    vault:
      uri: https://xxx.xxx.com:8200
      authentication: KUBERNETES
      kubernetes:
        role: abc
        kubernetes_path: path/to/k8s
        service_account_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token

**Error** 

    o.s.v.a.VaultLoginException: Cannot login using Kubernetes: invalid role name \"abc\";

When I try to login using curl with the same role and token, its success:

    VAULT_LOGIN="{\"role\":\"$SA_ROLE\", \"jwt\":\"$SA_JWT_TOKEN\"}"
    curl --request POST --data "$VAULT_LOGIN" https://xxx.xxx.com:8200/v1/auth/path/to/k8s/login

**Comment by mp911de** [comment] 2019-09-02 06:56
Can you make sure to use Apache HttpClient and increase the logging level to enable wire logging to inspect the outgoing payload for the login?

**Comment by mp911de** [comment] 2019-09-02 09:01
Looking at the implementation code, the slashes in the given path are URL-escaped (`%2F` instead of `/`). All authentication implementations suffer from that issue.

**Comment by hitenny** [comment] 2019-09-02 10:41
I have analyzed the spring-vault code and found an issue here: https://github.com/spring-projects/spring-vault/blob/ba7fd9b8b461f1bb52cbd74ae234079eac2fccef/spring-vault-core/src/main/java/org/springframework/vault/config/EnvironmentVaultConfiguration.java#L357

it does not read path from the configuration. I have fixed in my application by overriding this method: `protected ClientAuthentication kubeAuthentication()` in my application

**Comment by hitenny** [comment] 2019-09-02 10:43
> Can you make sure to use Apache HttpClient and increase the logging level to enable wire logging to inspect the outgoing payload for the login?

I logged the REST api call which pring-vault makes to Vault for login. Irrespective of the path configured in yaml, it is sending the default path `KUBERNETES` to vault. Root cause is provided in my previous comment

**Comment by mp911de** [comment] 2019-09-02 10:45
Thanks a lot. Can you file a bug report in Spring Cloud Vault? We cannot move tickets across organizations. 

Closing this one as the issue is in Spring Cloud Vault.

**Comment by hitenny** [comment] 2019-09-02 10:46
I am using spring-vault and not spring-cloud-vault. How is this related to spring-cloud-vault?

**Comment by mp911de** [comment] 2019-09-02 12:31
Sorry, that was an oversight on my end. I saw YAML-like properties and that's what we usually see in Spring Cloud.

`EnvironmentVaultConfiguration` is Spring Vault. We do not support path customization for authentication methods. If you like, feel free to submit a PR to add path support.

**Comment by hitenny** [comment] 2019-09-02 13:56
https://github.com/hitenny/spring-vault/pull/1

**Comment by mp911de** [comment] 2019-09-02 14:00
Thanks. The PR should target this repository. Also, it would make sense to support path customization for all authentication methods.

**Comment by hitenny** [comment] 2019-09-02 14:02
The path is specific to Kubernetes auth

**Comment by hitenny** [comment] 2019-09-02 14:04
https://github.com/spring-projects/spring-vault/pull/464

**Closed** 2019-11-14 15:46 UTC
Labels: type: enhancement
