### ISSUE TITLE
data being added in path of KV1 Engine, but not for KV2

### ISSUE THREAD

**Issue by ChrisJBurns** [spring-projects/spring-vault#738] opened 2022-11-17 12:43 UTC
We are using version `2.1.3.RELEASE` version of `spring-cloud-starter-vault-config` and for some reason we are getting issues when connecting to V2 KV Secret Engines.

I can confirm that when we point our config to a secret engine that is V1, the `/data/` path is inserted and used when trying to retrieve values. But when we switch to V2, the `/data/` path isn't inserted.

Is there some kind of reverse logic somewhere? We aren't doing anything special as far as I can see. 

### Bootstrap Config
```yaml
spring:
  cloud:
    vault:
      kv:
        enabled: true
      uri: [REDACTED]
      connection-timeout: 5000
      read-timeout: 15000
      authentication: TOKEN
      token: [REDACTED]
      config:
        order: -10
```

**Comment by mp911de** [comment] 2022-11-17 13:11
> we are getting issues

Do you happen to have further details? Stack traces, reproducers, more contextual details are appreciated.

**Comment by ChrisJBurns** [comment] 2022-11-17 13:24
I've also found that we are also doing stuff with the `VaultConfigurer` which makes things harder to drive via configuration.
```java

@PropertySource({"classpath:application.yaml"})
@Configuration
public class VaultConfig implements VaultConfigurer {
    @Value("${vault.location}")
    String vaultLocation;

    public VaultConfig() {
    }

    public void addSecretBackends(SecretBackendConfigurer configurer) {
        configurer.add("secrets/" + this.vaultLocation);
    }
}
```

It's worth adding, we are in the process of upgrading our libraries to use the latest versions of Spring Config Vault (so that we can take advantage of the Vault Agent Auto Auth and simpler config all round), but that may take a couple of weeks due to dev workload, so I'm trying to get the current versions up and running in a new cluster.

**Comment by mp911de** [comment] 2022-11-17 15:34
Thanks for the details. Spring Vault checks whether the given secret path maps to a v1 or a v2 backend by obtaining details from `sys/internal/ui/mounts/<path to secret>`.

That means that paths into the backend must not have the `data/` part after `secret/`.

If you enable debug logging for Spring Vault (and your HTTP client, Apache HTTP Client is ideal for debugging), then you get displayed which requests Spring Vault is issuing so you can trace down to what is happening. Additionally, you can debug the application by creating a breakpoint in the `LeaseAwareVaultPropertySource` listener to get hold of the loaded properties.

**Comment by mp911de** [comment] 2022-11-22 13:57
The `/data/` path segment is being inserted in `KeyValueDelegate`. See also `SecretLeaseContainer.doGetSecrets(…)`

**Comment by mp911de** [comment] 2023-03-17 09:32
Since there was no further activity and this ticket isn't actionable, we're closing this ticket. We're happy to revisit this ticket if we get more details or find something actionable about it.

**Closed by mp911de** 2023-03-17 09:32 UTC
Labels: status: waiting-for-feedback, status: waiting-for-triage
