### ISSUE TITLE
Keys of type different than "aes256-gcm" throw exception when method VaultTransitOperations.getKey(...) is called

### ISSUE THREAD

**Issue by luander** [spring-projects/spring-vault#149] opened 2017-09-28 13:08 UTC
I created a key of type **ecdsa-p256** using the following code:
```
VaultTransitKeyCreationRequest keyCreateRequest = VaultTransitKeyCreationRequest.builder()
    .type("ecdsa-p256").build();
vaultOperations.createKey(KEY_NAME, keyCreateRequest);
```
Key creation is fine, but when I try to get the details of the key I get the exception:

```
Can not deserialize instance of java.lang.Long out of START_OBJECT token at [Source: java.io.PushbackInputStream@705b2e8d; line: 1, column: 185] (through reference chain: org.springframework.vault.support.VaultResponseSupport["data"]->org.springframework.vault.core.VaultTransitKeyImpl["keys"]->java.util.LinkedHashMap["1"]); nested exception is com.fasterxml.jackson.databind.JsonMappingException: Can not deserialize instance of java.lang.Long out of START_OBJECT token at [Source: java.io.PushbackInputStream@705b2e8d; line: 1, column: 185] (through reference chain: org.springframework.vault.support.VaultResponseSupport["data"]->org.springframework.vault.core.VaultTransitKeyImpl["keys"]->java.util.LinkedHashMap["1"])
```

The exception is thrown because the response comes in the format:
```
"keys": {
    "1": {
        "creation_time": "2017-09-28T09:49:55.450882832Z",
        "name": "P-256",
        "public_key": "-----BEGIN PUBLIC KEY-----...-----END PUBLIC KEY-----\n"
    }
}
```
Instead of the standard format for **aes256-gcm** key which is:

```
"keys": {
    "1": 1442851412
}
```
A fix should include first reading the format of the key before trying to parse the keys field.

**Comment by mp911de** [comment] 2017-09-28 14:24
Thanks for reporting the issue. It just proves the general impression of the transit backend true, that it's not mature enough and things are quite in flux. The only possibility how to fix the issue is by changing `VaultTransitKey.getKeys()` from `Map<String, Long>` to `Map<String, Object>`.

**Comment by mp911de** [comment] 2017-10-02 13:43
That's fixed now.

**Closed by mp911de** 2017-10-02 13:43 UTC
Labels: bug

**Comment by zsolt-kali** [comment] 2018-01-05 15:27
Is the release date known already (that contains the fix)?

**Comment by mp911de** [comment] 2018-01-05 15:56
Expect 2.0 GA around mid-February. Updated the release date of 2.0 accordingly.
