### ISSUE TITLE
When restart a vault client , the token will be unavailable , I have to renew a token and restart all the client services

### ISSUE THREAD

**Issue by LuyuanBai** [spring-projects/spring-vault#255] opened 2018-06-11 05:38 UTC

**Comment by mp911de** [comment] 2018-06-11 06:54
Care to explain the scenario? What is happening and what would you expect to happen so we can reproduce the issue?

**Comment by LuyuanBai** [comment] 2018-06-11 07:01
1. When I use an invalid token to access Vault, it will cause the valid token to invalid.
2. When I restart the Vault client (a service), the same issue will show up. but not so often.

**Comment by mp911de** [comment] 2018-06-11 07:02
Can you post the metadata of the token?

**Comment by LuyuanBai** [comment] 2018-06-11 07:17
What's the metadata of the token, the configuration?

**Comment by mp911de** [comment] 2018-06-11 08:05
The output of Vault CLI's `vault token lookup`. Example:

```
$ vault token lookup bc80d807-2952-33e3-c8ae-661596c9623e
Key                 Value
---                 -----
accessor            16674493-1f8f-d3c7-4290-bd844259e394
creation_time       1528704259
creation_ttl        0
display_name        token
entity_id           n/a
expire_time         <nil>
explicit_max_ttl    0
id                  bc80d807-2952-33e3-c8ae-661596c9623e
issue_time          2018-06-11T10:04:19.052848876+02:00
meta                <nil>
num_uses            0
orphan              false
path                auth/token/create
policies            [root]
renewable           false
ttl                 0
```

**Comment by LuyuanBai** [comment] 2018-06-11 08:20
[root@infbjvm109 vault_0.10.0_linux_amd64]# vault login ef100e61-b60a-8372-2ef1-e8ab733795a3
WARNING! The VAULT_TOKEN environment variable is set! This takes precedence
over the value set by this command. To use the value set by this command,
unset the VAULT_TOKEN environment variable or set it to the token displayed
below.

Success! You are now authenticated. The token information displayed below
is already stored in the token helper. You do NOT need to run "vault login"
again. Future Vault requests will automatically use this token.

Key                Value
---                -----
token              ef100e61-b60a-8372-2ef1-e8ab733795a3
token_accessor     5a4f8b02-6ff3-3dbf-8aef-1a4b55296522
token_duration     ∞
token_renewable    false
token_policies     [root]
 
but when execute 
[root@infbjvm109 vault_0.10.0_linux_amd64]# vault token lookup ef100e61-b60a-8372-2ef1-e8ab733795a3
Error looking up token: Error making API request.

URL: POST http://127.0.0.1:8200/v1/auth/token/lookup
Code: 403. Errors:

* permission denied

**Comment by mp911de** [comment] 2018-06-11 08:38
Sorry, we can't assist you on Vault issues. Please come back once you've solved basic Vault issues.

**Comment by mp911de** [comment] 2018-06-20 06:52
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by mp911de** 2018-06-20 06:52 UTC
Labels: status: cannot-reproduce
